language: node_js
node_js:
  - '12'

services:
  - docker

before_install:
  - npm i @microservices/oms

script:
  - npx oms build
  - |
    output="$(npx oms run --silent format -a data='[1, 2]' | jq -c .)"
    if [ "$output" != '--- "[1, 2]"' ] ; then echo "$output"; exit 1; fi
