version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14
    working_directory: ~/omg

    steps:
      - checkout
      - setup_remote_docker
      - run: npm i omg
      - run: npx omg exec parse -a data="- item"
